language: go

go:
  - 1.20.x

# let us have speedy Docker-based Travis workers
sudo: true

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
