name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Set up Go 1.20
        uses: actions/setup-go@v2

      - name: install dependencies
        run: |
          go get -v -t -d ./...
        with:
          go-version: 1.20

      - name: go build
        run: go build -v ./...

      - name: go test
        run: go test -v ./...

      - name: benchmark tests
        run: go test -timeout 300s -bench=. -benchmem